export type ServiceState = "ready" | "degraded" | "optional unavailable" | "unknown";
export interface ModelInfo { model_version?: string; model_status?: string; feature_schema_version?: string; supported_intervals: string[]; model_age_days?: number; data_age_hours?: number; }
export interface NewsEvent { id: string; source?: string; title: string; published_at: string; event_type: string; sentiment: string; impact_direction: string; impact_probability: number; url?: string | null; }
export interface NewsContext { symbol: string; window_hours: number; news_count: number; sentiment_score: number; positive_count: number; negative_count: number; high_impact_count: number; risk_level: string; top_events: NewsEvent[]; }
export interface Decision { id?: number; symbol: string; interval: string; signal_detected: boolean; trade_allowed: boolean; active_strategies: string[]; selected_strategy?: string | null; raw_prob_good_trade?: number | null; prob_good_trade?: number | null; threshold?: number | null; risk_level?: string | null; signal_close_price?: number | null; planned_entry_price?: number | null; risk_parameters?: { stop_loss_price: number; take_profit_price: number; recommended_position_size: number; recommended_position_notional: number; }; news_context?: NewsContext | null; reason: string; model_version?: string | null; }
export interface StoredDecision { id: number; symbol: string; created_at: string; selected_strategy?: string | null; probability?: number | null; trade_allowed: boolean; news_risk_level?: string | null; outcome_status?: string | null; }
export interface Health { status?: string; readiness?: string; backend?: string; ml_service?: string; news_service?: string; llm?: string; telegram?: string; database?: string; }
export interface PaperPortfolio { portfolio_id: string; starting_balance: number; current_equity: number; cash: number; gross_exposure: number; open_risk: number; realized_pnl: number; unrealized_pnl: number; max_drawdown: number; }
export interface PaperPosition { id: string; symbol: string; strategy: string; status: string; notional: number; opened_at?: string | null; exit_at?: string | null; realized_pnl?: number | null; }
export interface GeoEvent { event_id: string; event_type: string; known_at: string; event_time?: string | null; countries: string[]; persons: string[]; organizations: string[]; severity: number; crypto_relevance: number; risk_on_off_direction: string; source_count: number; }
export interface AgentResponse { answer: string; uncertainty: number; model_used: string; degraded: boolean; evidence: Array<{kind:string;source:string;record_id?:string|null;url?:string|null;timestamp?:string|null;data:Record<string,unknown>}>; }
