FROM python:3.11-slim

WORKDIR /app

COPY app/backend/api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/workspace/app/backend/api

EXPOSE 8000

CMD ["uvicorn", "app.backend.api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]