# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml/v1/ml.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml/v1/ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eml/v1/ml.proto\x12\x02ml\"\xb2\x01\n\x0eSignalFeatures\x12\x0e\n\x06rsi_14\x18\x01 \x01(\x01\x12\x10\n\x08return_1\x18\x02 \x01(\x01\x12\x10\n\x08return_6\x18\x03 \x01(\x01\x12\x11\n\treturn_24\x18\x04 \x01(\x01\x12\x15\n\rvolatility_24\x18\x05 \x01(\x01\x12\x15\n\rvolume_zscore\x18\x06 \x01(\x01\x12\x16\n\x0etrend_strength\x18\x07 \x01(\x01\x12\x13\n\x0bma_distance\x18\x08 \x01(\x01\"\x87\x01\n\x1bPredictSignalQualityRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12$\n\x08\x66\x65\x61tures\x18\x05 \x01(\x0b\x32\x12.ml.SignalFeatures\"u\n\x1cPredictSignalQualityResponse\x12\r\n\x05p_win\x18\x01 \x01(\x01\x12\x1b\n\x13\x65xpected_return_pct\x18\x02 \x01(\x01\x12\x12\n\nrisk_level\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t2f\n\tMLService\x12Y\n\x14PredictSignalQuality\x12\x1f.ml.PredictSignalQualityRequest\x1a .ml.PredictSignalQualityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml.v1.ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALFEATURES']._serialized_start=23
  _globals['_SIGNALFEATURES']._serialized_end=201
  _globals['_PREDICTSIGNALQUALITYREQUEST']._serialized_start=204
  _globals['_PREDICTSIGNALQUALITYREQUEST']._serialized_end=339
  _globals['_PREDICTSIGNALQUALITYRESPONSE']._serialized_start=341
  _globals['_PREDICTSIGNALQUALITYRESPONSE']._serialized_end=458
  _globals['_MLSERVICE']._serialized_start=460
  _globals['_MLSERVICE']._serialized_end=562
# @@protoc_insertion_point(module_scope)
