# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ml.v1 import ml_pb2 as ml_dot_v1_dot_ml__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml/v1/ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictSignalQuality = channel.unary_unary(
                '/ml.v1.MLService/PredictSignalQuality',
                request_serializer=ml_dot_v1_dot_ml__pb2.PredictSignalQualityRequest.SerializeToString,
                response_deserializer=ml_dot_v1_dot_ml__pb2.PredictSignalQualityResponse.FromString,
                _registered_method=True)


class MLServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictSignalQuality(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictSignalQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictSignalQuality,
                    request_deserializer=ml_dot_v1_dot_ml__pb2.PredictSignalQualityRequest.FromString,
                    response_serializer=ml_dot_v1_dot_ml__pb2.PredictSignalQualityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml.v1.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml.v1.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictSignalQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.v1.MLService/PredictSignalQuality',
            ml_dot_v1_dot_ml__pb2.PredictSignalQualityRequest.SerializeToString,
            ml_dot_v1_dot_ml__pb2.PredictSignalQualityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
