# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml/v1/ml.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml/v1/ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eml/v1/ml.proto\x12\x05ml.v1\"f\n\x06\x43\x61ndle\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\"v\n\x1bPredictSignalQualityRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\x15\n\rstrategy_name\x18\x03 \x01(\t\x12\x1e\n\x07\x63\x61ndles\x18\x04 \x03(\x0b\x32\r.ml.v1.Candle\"\xa0\x01\n\x1cPredictSignalQualityResponse\x12\x17\n\x0fprob_good_trade\x18\x01 \x01(\x01\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x15\n\rtrade_allowed\x18\x03 \x01(\x08\x12\x11\n\tthreshold\x18\x04 \x01(\x01\x12\x12\n\nrisk_level\x18\x05 \x01(\t\x12\x15\n\rmodel_version\x18\x06 \x01(\t2l\n\tMLService\x12_\n\x14PredictSignalQuality\x12\".ml.v1.PredictSignalQualityRequest\x1a#.ml.v1.PredictSignalQualityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml.v1.ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDLE']._serialized_start=25
  _globals['_CANDLE']._serialized_end=127
  _globals['_PREDICTSIGNALQUALITYREQUEST']._serialized_start=129
  _globals['_PREDICTSIGNALQUALITYREQUEST']._serialized_end=247
  _globals['_PREDICTSIGNALQUALITYRESPONSE']._serialized_start=250
  _globals['_PREDICTSIGNALQUALITYRESPONSE']._serialized_end=410
  _globals['_MLSERVICE']._serialized_start=412
  _globals['_MLSERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
